config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/integration')
  get 'integration', to: 'application#integration'
  # get 'example', to: 'application#example'
  get 'documentation', to: 'application#documentation'

  get 'api', to: 'api#api', as: :api
  resources :widgets, only: [:index, :show], param: :name
  resources :events

  # get 'api', format: :js, to: redirect { |path_params, req| ActionController::Base.helpers.asset_path("#{'/assets/' if Rails.env.development?}api.js") }

  # get '/scripts/widget', to: 'scripts#widget'
  # match '/widget/:name', to: 'widgets#show', via: [:get, :post]
  # get '/', to: 'widgets#show'
  # get '/widgets', to: 'widgets#index'
end

app/models/application_record.rb
# class ApplicationRecord < ActiveRecord::Base
#   self.abstract_class = true
# end

app/models/event.rb
# class Event < ApplicationRecord
# end

app/models/widget.rb
class Widget
  attr_reader :name
  attr_accessor :id

  def self.names
    %w(Sample Dummy)
  end

  def self.all
    @all ||= Widget.names.map do |name|
      Widget.new(name)
    end
  end

  def self.available(params = {})
    Widget.all.select do |widget|
      widget.available?(params)
    end
  end

  def self.find(_name)
    result = Widget.all.find do |widget|
      widget.name == _name
    end
    raise ActiveRecord::RecordNotFound unless result
    result
  end

  def available?(params = {})
    policy.available?(params)
  end

  def options
    defaults = {
      delay: 0,
      width: 300,
      height: 200,
    }
    defaults.merge policy.options
  end

  def initialize(_name, options = {})
    @name = _name
  end

  def policy
    "Widgets::#{name}::Policy".classify.constantize
  end

  def template
    "#{name.underscore}/content"
  end

  def content
    WidgetsController.render template, locals: { widget: self }
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
  wrap_parameters false

  prepend_view_path 'app/assets/javascripts'

  def api
    respond_to do |format|
      # format.js {
      #   if Rails.env.production?
      #     redirect_to ActionController::Base.helpers.asset_path("api.js", format: :js)
      #     redirect_to ActionController::Base.helpers.asset_path("/assets/api.js")
      #   else
      #     render file: 'api.js'
      #   end
      # }
      # format.js { redirect_to '/assets/api.js' }
      format.js { render file: 'api.js' }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def integration
  end

  def example
  end

  def documentation
  end

  def insert
    respond_to do |format|
      format.js
    end
  end

  private

  def allow_iframe
    # response.headers['X-Frame-Options'] = 'ALLOW-FROM localhost'
    response.headers.except! 'X-Frame-Options'
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  skip_before_action :verify_authenticity_token
  wrap_parameters false

  prepend_view_path 'app/components/widgets'

  after_action :allow_iframe, only: [:show]

  def index
    widgets = Widget.available(params)
    uri = URI.parse(request.original_url)
    uri.path = ''
    uri.query = nil
    respond_to do |format|
      format.js { render :index, layout: false, locals: { widgets: widgets, uri: uri } }
      format.html { render :index }
    end
  end

  def show
    widget = Widget.find(params[:name])
    widget.id = params[:id]
    if widget
      respond_to do |format|
        format.js { render :show, layout: false, locals: { widget: widget } }
        format.html { render template: widget.template, layout: false, locals: { widget: widget } }
        format.json {
          render json: widget.to_json
        }
      end
    else
      head 404
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sample_widget_params
    JSON.parse File.read(Rails.root.join('test', 'fixtures', 'requests', 'sample.json'))
  end

  def app_host
    ENV["APP_HOST"]
  end

  def app_port
    ENV['APP_PORT']
  end
end

app/views/application/_menu.html.erb
<h1>Widget API</h1>
<%= link_to 'Интеграция', integration_path %> |
<%= link_to 'Документация', documentation_path %> |
<%= link_to 'Виджеты', widgets_path %> |
<%= link_to 'API', api_path(format: 'js'), target: 'blank'  %>
<hr>

app/views/application/documentation.html.erb
<%= render partial: 'menu' %>
<h2>Документация</h2>

<h3>Показать виджет</h3>

<pre>
  <code>
    showWidget(name)

    name - строка, имя виджета
  </code>
</pre>

<h3>Закрыть виджет</h3>

<pre>
  <code>
    closeWidget(name)

    name - строка, имя виджета
  </code>
</pre>

<h3>Отправить виджет</h3>

<pre>
  <code>
    submitWidget(name)

    name - строка, имя виджета
  </code>
</pre>

<h3>Добавить коллбэк</h3>

<pre>
  <code>
    addCallback(topic, callback)

    topic - строка, имя коллбэка
    возможные значения

    closeWidget
    submitWidget
    showWidget
  </code>
</pre>

<h3>Убрать коллбэк</h3>

<pre>
  <code>
    removeCallback(topic, callback)
  </code>
</pre>

app/views/application/example.html.erb
<%= render partial: 'menu' %>

<h2>Example</h2>

<p>The source code of this example can be found at <code>app/views/application/index.html</code></p>

<p>Insert tag <code>script</code> immidiately after opening <code>body</code> tag</p>

<p>
  <strong>Script url of this examples</strong> is:
  <pre style="word-break: break-all; width: 500px;"><code><%= api_path(format: :js, params: sample_widget_params, host: app_host, port: app_port, only_path: !Rails.env.producion?) %></code></pre>
</p>

<h3>Dummy widget</h3>
<p>Empty widget for test purposes.</p>

<h3>Sample widget</h3>
<p>
  <strong>Params:</strong>
  <pre><code><%= JSON.pretty_generate sample_widget_params %></code></pre>
</p>

<p>
  <strong>Options:</strong>
  <pre><code><%= JSON.pretty_generate Widgets::Sample::Policy.options %></code></pre>
</p>

app/views/application/insert.js.erb
(function() {
  if ("undefined" === typeof widget_api) {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.async = true;
    script.src = "<%= ENV['WIDGET_API_URL'] %>";
    var target = document.getElementsByTagName("head")[0];
    target.appendChild(script);
    widget_api = {};
    widget_api.queue = [];
    methods = ['showWidget', 'closeWidget', 'submitWidget', 'addCallback', 'removeCallback'];
    function enqueue_method(name, args) {
      return function() {
        window.widget_api.queue.push(name, arguments);
      }
    }
    for (var i = 0; i < methods.length; i++) {
      widget_api[methods[i]] = enqueue_method(methods[i]);
    }
  }
})();

app/views/application/integration.html.erb
<%= render partial: 'menu' %>

<h2>Интеграция</h2>

<p>Вставьте на страницу сразу перед закрывающимся тегом <code>head</code> тег <code>script</code> со следующим содержимым:</p>

<pre style="word-break: break-all; width: 500px;"><code><%= render file: Rails.root.join('app', 'views', 'application', 'insert.js.erb') %> </pre></code>

<p>
  <code>widget_api_url</code> должен содержать полный пусть к <code>api.js</code>, например:
</p>

<pre><code>localhost:4000/api.js</code></pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WidgetAPI</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/widgets/_handlers.html.erb
<script type="text/javascript">
  function submitWidget(name) {
    document.getElementsByTagName("body")[0].remove();
    var data = ["submitWidget", [name]];
    top.postMessage(JSON.stringify(data), "*");
  };
  function closeWidget(name) {
    document.getElementsByTagName("body")[0].remove();
    var data = ["closeWidget", [name]];
    top.postMessage(JSON.stringify(data), "*");
  };
  var elements = document.querySelectorAll("[data-widget='close']");
  for (index = elements.length - 1; index >= 0; index--) {
    elements[index].onclick = function(){ closeWidget("<%= widget.name %>") };
  }
  var elements = document.querySelectorAll("[data-widget='submit']");
  for (index = elements.length - 1; index >= 0; index--) {
    elements[index].onsubmit = function(){ submitWidget("<%= widget.name %>"); return false; };
  }
</script>

app/views/widgets/index.html.erb
<%= render partial: 'menu' %>

<h2>Виджеты</h2>

<% Widget.all.each do |widget| %>
  <%= link_to widget.name, widget_path(widget.name), target: '_blank' %>
  <br>
<% end %>

app/views/widgets/index.js.erb
<% widgets.each_with_index do |widget, index| %>
  <%= render widget %>
<% end %>

app/views/widgets/show.js.erb
(function(_document) {
var options = <%= raw widget.options.to_json %>;
var iframe = _document.createElement("iframe");
iframe.style = "opacity: 1; z-index: 999999; margin: 20px; background-color: white; border: 1px solid; display: none; position: absolute;";
iframe.style.width = options.width.toString() + "px";
iframe.style.height = options.height.toString() + "px";
iframe.src = "<%= widget_url(widget.name, host: 'localhost:4000') %>";
iframe.frameBorder = 0;
iframe.name = "<%= widget.name %>";
_document.body.insertBefore(iframe, _document.body.firstChild); // TODO: add only after iframe is loaded
// _document.body.insertBefore(iframe, _document.body.lastChild.nextSibling);
setTimeout(function(){
  iframe.style.display = 'inline';
  widget_api.fireCallback("showWidget", {name: iframe.name});
}, options.delay);
})(document);